name: vroom_core
description: A new flutter plugin project.
version: 0.0.1
homepage:

environment:
  sdk: ">=2.16.2 <3.0.0"
  flutter: ">=2.5.0"

dependencies:
  flutter:
    sdk: flutter
  cloud_firestore: ^3.1.14
  flutter_dotenv: ^5.0.2
  flutterwave_standard: ^1.0.3
  firebase_core: ^1.16.0
  firebase_auth: ^3.3.17
  firebase_storage: ^10.2.15
  image_picker: ^0.8.5
  provider: ^6.0.2
  intl: ^0.17.0
  url_launcher: ^6.0.20

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.4

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  # This section identifies this Flutter project as a plugin project.
  # The 'pluginClass' and Android 'package' identifiers should not ordinarily
  # be modified. They are used by the tooling to maintain consistency when
  # adding or updating assets for this project.
  plugin:
    platforms:
      android:
        package: com.example.vroom_core
        pluginClass: VroomCorePlugin
      ios:
        pluginClass: VroomCorePlugin

  assets:
    - .env